USE [master]
GO

/****** Object:  Database [EmployeeLeaveMangDB]    Script Date: 18-03-2022 10:52:32 ******/
CREATE DATABASE [EmployeeLeaveMangDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'EmployeeLeaveMangDB', FILENAME = N'C:\Users\DELL\AppData\Local\Microsoft\Microsoft SQL Server Local DB\Instances\MSSQLLocalDB\EmployeeLeaveMangDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'EmployeeLeaveMangDB_log', FILENAME = N'C:\Users\DELL\AppData\Local\Microsoft\Microsoft SQL Server Local DB\Instances\MSSQLLocalDB\EmployeeLeaveMangDB.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [EmployeeLeaveMangDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [EmployeeLeaveMangDB] SET ANSI_NULL_DEFAULT ON 
GO

ALTER DATABASE [EmployeeLeaveMangDB] SET ANSI_NULLS ON 
GO

ALTER DATABASE [EmployeeLeaveMangDB] SET ANSI_PADDING ON 
GO

ALTER DATABASE [EmployeeLeaveMangDB] SET ANSI_WARNINGS ON 
GO

ALTER DATABASE [EmployeeLeaveMangDB] SET ARITHABORT ON 
GO

ALTER DATABASE [EmployeeLeaveMangDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [EmployeeLeaveMangDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [EmployeeLeaveMangDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [EmployeeLeaveMangDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [EmployeeLeaveMangDB] SET CURSOR_DEFAULT  LOCAL 
GO

ALTER DATABASE [EmployeeLeaveMangDB] SET CONCAT_NULL_YIELDS_NULL ON 
GO

ALTER DATABASE [EmployeeLeaveMangDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [EmployeeLeaveMangDB] SET QUOTED_IDENTIFIER ON 
GO

ALTER DATABASE [EmployeeLeaveMangDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [EmployeeLeaveMangDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [EmployeeLeaveMangDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [EmployeeLeaveMangDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [EmployeeLeaveMangDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [EmployeeLeaveMangDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [EmployeeLeaveMangDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [EmployeeLeaveMangDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [EmployeeLeaveMangDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [EmployeeLeaveMangDB] SET RECOVERY FULL 
GO

ALTER DATABASE [EmployeeLeaveMangDB] SET  MULTI_USER 
GO

ALTER DATABASE [EmployeeLeaveMangDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [EmployeeLeaveMangDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [EmployeeLeaveMangDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [EmployeeLeaveMangDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [EmployeeLeaveMangDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [EmployeeLeaveMangDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [EmployeeLeaveMangDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [EmployeeLeaveMangDB] SET  READ_WRITE 
GO

